/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as CitaTokenRouteImport } from './routes/cita.$token'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard.agenda'
import { Route as DashboardAjustesRouteImport } from './routes/dashboard.ajustes'
import { Route as DashboardCitasRouteImport } from './routes/dashboard.citas'
import { Route as DashboardClientesRouteImport } from './routes/dashboard.clientes'
import { Route as DashboardHorariosRouteImport } from './routes/dashboard.horarios'
import { Route as DashboardPlanesRouteImport } from './routes/dashboard.planes'
import { Route as DashboardProfesionalesRouteImport } from './routes/dashboard.profesionales'
import { Route as DashboardServiciosRouteImport } from './routes/dashboard.servicios'
import { Route as DashboardSucursalesRouteImport } from './routes/dashboard.sucursales'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitaTokenRoute = CitaTokenRouteImport.update({
  id: '/cita/$token',
  path: '/cita/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAjustesRoute = DashboardAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitasRoute = DashboardCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesRoute = DashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHorariosRoute = DashboardHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlanesRoute = DashboardPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfesionalesRoute = DashboardProfesionalesRouteImport.update({
  id: '/profesionales',
  path: '/profesionales',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServiciosRoute = DashboardServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSucursalesRoute = DashboardSucursalesRouteImport.update({
  id: '/sucursales',
  path: '/sucursales',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/inicio': typeof InicioRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/b/$slug': typeof BSlugRoute
  '/cita/$token': typeof CitaTokenRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/ajustes': typeof DashboardAjustesRoute
  '/dashboard/citas': typeof DashboardCitasRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/horarios': typeof DashboardHorariosRoute
  '/dashboard/planes': typeof DashboardPlanesRoute
  '/dashboard/profesionales': typeof DashboardProfesionalesRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/sucursales': typeof DashboardSucursalesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/inicio': typeof InicioRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/b/$slug': typeof BSlugRoute
  '/cita/$token': typeof CitaTokenRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/ajustes': typeof DashboardAjustesRoute
  '/dashboard/citas': typeof DashboardCitasRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/horarios': typeof DashboardHorariosRoute
  '/dashboard/planes': typeof DashboardPlanesRoute
  '/dashboard/profesionales': typeof DashboardProfesionalesRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/sucursales': typeof DashboardSucursalesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/inicio': typeof InicioRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/b/$slug': typeof BSlugRoute
  '/cita/$token': typeof CitaTokenRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/ajustes': typeof DashboardAjustesRoute
  '/dashboard/citas': typeof DashboardCitasRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/horarios': typeof DashboardHorariosRoute
  '/dashboard/planes': typeof DashboardPlanesRoute
  '/dashboard/profesionales': typeof DashboardProfesionalesRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/sucursales': typeof DashboardSucursalesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/inicio'
    | '/onboarding'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/b/$slug'
    | '/cita/$token'
    | '/dashboard/agenda'
    | '/dashboard/ajustes'
    | '/dashboard/citas'
    | '/dashboard/clientes'
    | '/dashboard/horarios'
    | '/dashboard/planes'
    | '/dashboard/profesionales'
    | '/dashboard/servicios'
    | '/dashboard/sucursales'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/inicio'
    | '/onboarding'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/b/$slug'
    | '/cita/$token'
    | '/dashboard/agenda'
    | '/dashboard/ajustes'
    | '/dashboard/citas'
    | '/dashboard/clientes'
    | '/dashboard/horarios'
    | '/dashboard/planes'
    | '/dashboard/profesionales'
    | '/dashboard/servicios'
    | '/dashboard/sucursales'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/inicio'
    | '/onboarding'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/b/$slug'
    | '/cita/$token'
    | '/dashboard/agenda'
    | '/dashboard/ajustes'
    | '/dashboard/citas'
    | '/dashboard/clientes'
    | '/dashboard/horarios'
    | '/dashboard/planes'
    | '/dashboard/profesionales'
    | '/dashboard/servicios'
    | '/dashboard/sucursales'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  InicioRoute: typeof InicioRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TerminosRoute: typeof TerminosRoute
  BSlugRoute: typeof BSlugRoute
  CitaTokenRoute: typeof CitaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cita/$token': {
      id: '/cita/$token'
      path: '/cita/$token'
      fullPath: '/cita/$token'
      preLoaderRoute: typeof CitaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ajustes': {
      id: '/dashboard/ajustes'
      path: '/ajustes'
      fullPath: '/dashboard/ajustes'
      preLoaderRoute: typeof DashboardAjustesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/citas': {
      id: '/dashboard/citas'
      path: '/citas'
      fullPath: '/dashboard/citas'
      preLoaderRoute: typeof DashboardCitasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/horarios': {
      id: '/dashboard/horarios'
      path: '/horarios'
      fullPath: '/dashboard/horarios'
      preLoaderRoute: typeof DashboardHorariosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/planes': {
      id: '/dashboard/planes'
      path: '/planes'
      fullPath: '/dashboard/planes'
      preLoaderRoute: typeof DashboardPlanesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profesionales': {
      id: '/dashboard/profesionales'
      path: '/profesionales'
      fullPath: '/dashboard/profesionales'
      preLoaderRoute: typeof DashboardProfesionalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/servicios': {
      id: '/dashboard/servicios'
      path: '/servicios'
      fullPath: '/dashboard/servicios'
      preLoaderRoute: typeof DashboardServiciosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sucursales': {
      id: '/dashboard/sucursales'
      path: '/sucursales'
      fullPath: '/dashboard/sucursales'
      preLoaderRoute: typeof DashboardSucursalesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardAjustesRoute: typeof DashboardAjustesRoute
  DashboardCitasRoute: typeof DashboardCitasRoute
  DashboardClientesRoute: typeof DashboardClientesRoute
  DashboardHorariosRoute: typeof DashboardHorariosRoute
  DashboardPlanesRoute: typeof DashboardPlanesRoute
  DashboardProfesionalesRoute: typeof DashboardProfesionalesRoute
  DashboardServiciosRoute: typeof DashboardServiciosRoute
  DashboardSucursalesRoute: typeof DashboardSucursalesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardAjustesRoute: DashboardAjustesRoute,
  DashboardCitasRoute: DashboardCitasRoute,
  DashboardClientesRoute: DashboardClientesRoute,
  DashboardHorariosRoute: DashboardHorariosRoute,
  DashboardPlanesRoute: DashboardPlanesRoute,
  DashboardProfesionalesRoute: DashboardProfesionalesRoute,
  DashboardServiciosRoute: DashboardServiciosRoute,
  DashboardSucursalesRoute: DashboardSucursalesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  InicioRoute: InicioRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacidadRoute: PrivacidadRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TerminosRoute: TerminosRoute,
  BSlugRoute: BSlugRoute,
  CitaTokenRoute: CitaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
