/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard.agenda'
import { Route as DashboardAjustesRouteImport } from './routes/dashboard.ajustes'
import { Route as DashboardCitasRouteImport } from './routes/dashboard.citas'
import { Route as DashboardClientesRouteImport } from './routes/dashboard.clientes'
import { Route as DashboardEquipoRouteImport } from './routes/dashboard.equipo'
import { Route as DashboardHorariosRouteImport } from './routes/dashboard.horarios'
import { Route as DashboardIntegracionesRouteImport } from './routes/dashboard.integraciones'
import { Route as DashboardPlanesRouteImport } from './routes/dashboard.planes'
import { Route as DashboardProfesionalesRouteImport } from './routes/dashboard.profesionales'
import { Route as DashboardServiciosRouteImport } from './routes/dashboard.servicios'
import { Route as DashboardSucursalesRouteImport } from './routes/dashboard.sucursales'
import { Route as ApiPublicSendRemindersRouteImport } from './routes/api.public.send-reminders'
import { Route as ApiPublicSendWebhooksRouteImport } from './routes/api.public.send-webhooks'
import { Route as ApiPublicCalendarTokenRouteImport } from './routes/api.public.calendar.$token'
import { Route as ApiPublicV1AppointmentsRouteImport } from './routes/api.public.v1.appointments'
import { Route as ApiPublicV1ClientsRouteImport } from './routes/api.public.v1.clients'
import { Route as ApiPublicV1ServicesRouteImport } from './routes/api.public.v1.services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAjustesRoute = DashboardAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitasRoute = DashboardCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesRoute = DashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipoRoute = DashboardEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHorariosRoute = DashboardHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegracionesRoute = DashboardIntegracionesRouteImport.update({
  id: '/integraciones',
  path: '/integraciones',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlanesRoute = DashboardPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfesionalesRoute = DashboardProfesionalesRouteImport.update({
  id: '/profesionales',
  path: '/profesionales',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServiciosRoute = DashboardServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSucursalesRoute = DashboardSucursalesRouteImport.update({
  id: '/sucursales',
  path: '/sucursales',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicSendRemindersRoute = ApiPublicSendRemindersRouteImport.update({
  id: '/api/public/send-reminders',
  path: '/api/public/send-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendWebhooksRoute = ApiPublicSendWebhooksRouteImport.update({
  id: '/api/public/send-webhooks',
  path: '/api/public/send-webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarTokenRoute = ApiPublicCalendarTokenRouteImport.update({
  id: '/api/public/calendar/$token',
  path: '/api/public/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AppointmentsRoute = ApiPublicV1AppointmentsRouteImport.update({
  id: '/api/public/v1/appointments',
  path: '/api/public/v1/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ClientsRoute = ApiPublicV1ClientsRouteImport.update({
  id: '/api/public/v1/clients',
  path: '/api/public/v1/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ServicesRoute = ApiPublicV1ServicesRouteImport.update({
  id: '/api/public/v1/services',
  path: '/api/public/v1/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/b/$slug': typeof BSlugRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/ajustes': typeof DashboardAjustesRoute
  '/dashboard/citas': typeof DashboardCitasRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/equipo': typeof DashboardEquipoRoute
  '/dashboard/horarios': typeof DashboardHorariosRoute
  '/dashboard/integraciones': typeof DashboardIntegracionesRoute
  '/dashboard/planes': typeof DashboardPlanesRoute
  '/dashboard/profesionales': typeof DashboardProfesionalesRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/sucursales': typeof DashboardSucursalesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/send-reminders': typeof ApiPublicSendRemindersRoute
  '/api/public/send-webhooks': typeof ApiPublicSendWebhooksRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/v1/appointments': typeof ApiPublicV1AppointmentsRoute
  '/api/public/v1/clients': typeof ApiPublicV1ClientsRoute
  '/api/public/v1/services': typeof ApiPublicV1ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/b/$slug': typeof BSlugRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/ajustes': typeof DashboardAjustesRoute
  '/dashboard/citas': typeof DashboardCitasRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/equipo': typeof DashboardEquipoRoute
  '/dashboard/horarios': typeof DashboardHorariosRoute
  '/dashboard/integraciones': typeof DashboardIntegracionesRoute
  '/dashboard/planes': typeof DashboardPlanesRoute
  '/dashboard/profesionales': typeof DashboardProfesionalesRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/sucursales': typeof DashboardSucursalesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/send-reminders': typeof ApiPublicSendRemindersRoute
  '/api/public/send-webhooks': typeof ApiPublicSendWebhooksRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/v1/appointments': typeof ApiPublicV1AppointmentsRoute
  '/api/public/v1/clients': typeof ApiPublicV1ClientsRoute
  '/api/public/v1/services': typeof ApiPublicV1ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/b/$slug': typeof BSlugRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/ajustes': typeof DashboardAjustesRoute
  '/dashboard/citas': typeof DashboardCitasRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/equipo': typeof DashboardEquipoRoute
  '/dashboard/horarios': typeof DashboardHorariosRoute
  '/dashboard/integraciones': typeof DashboardIntegracionesRoute
  '/dashboard/planes': typeof DashboardPlanesRoute
  '/dashboard/profesionales': typeof DashboardProfesionalesRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/sucursales': typeof DashboardSucursalesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/send-reminders': typeof ApiPublicSendRemindersRoute
  '/api/public/send-webhooks': typeof ApiPublicSendWebhooksRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/v1/appointments': typeof ApiPublicV1AppointmentsRoute
  '/api/public/v1/clients': typeof ApiPublicV1ClientsRoute
  '/api/public/v1/services': typeof ApiPublicV1ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/b/$slug'
    | '/dashboard/agenda'
    | '/dashboard/ajustes'
    | '/dashboard/citas'
    | '/dashboard/clientes'
    | '/dashboard/equipo'
    | '/dashboard/horarios'
    | '/dashboard/integraciones'
    | '/dashboard/planes'
    | '/dashboard/profesionales'
    | '/dashboard/servicios'
    | '/dashboard/sucursales'
    | '/dashboard/'
    | '/api/public/send-reminders'
    | '/api/public/send-webhooks'
    | '/api/public/calendar/$token'
    | '/api/public/v1/appointments'
    | '/api/public/v1/clients'
    | '/api/public/v1/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/b/$slug'
    | '/dashboard/agenda'
    | '/dashboard/ajustes'
    | '/dashboard/citas'
    | '/dashboard/clientes'
    | '/dashboard/equipo'
    | '/dashboard/horarios'
    | '/dashboard/integraciones'
    | '/dashboard/planes'
    | '/dashboard/profesionales'
    | '/dashboard/servicios'
    | '/dashboard/sucursales'
    | '/dashboard'
    | '/api/public/send-reminders'
    | '/api/public/send-webhooks'
    | '/api/public/calendar/$token'
    | '/api/public/v1/appointments'
    | '/api/public/v1/clients'
    | '/api/public/v1/services'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/b/$slug'
    | '/dashboard/agenda'
    | '/dashboard/ajustes'
    | '/dashboard/citas'
    | '/dashboard/clientes'
    | '/dashboard/equipo'
    | '/dashboard/horarios'
    | '/dashboard/integraciones'
    | '/dashboard/planes'
    | '/dashboard/profesionales'
    | '/dashboard/servicios'
    | '/dashboard/sucursales'
    | '/dashboard/'
    | '/api/public/send-reminders'
    | '/api/public/send-webhooks'
    | '/api/public/calendar/$token'
    | '/api/public/v1/appointments'
    | '/api/public/v1/clients'
    | '/api/public/v1/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TerminosRoute: typeof TerminosRoute
  BSlugRoute: typeof BSlugRoute
  ApiPublicSendRemindersRoute: typeof ApiPublicSendRemindersRoute
  ApiPublicSendWebhooksRoute: typeof ApiPublicSendWebhooksRoute
  ApiPublicCalendarTokenRoute: typeof ApiPublicCalendarTokenRoute
  ApiPublicV1AppointmentsRoute: typeof ApiPublicV1AppointmentsRoute
  ApiPublicV1ClientsRoute: typeof ApiPublicV1ClientsRoute
  ApiPublicV1ServicesRoute: typeof ApiPublicV1ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ajustes': {
      id: '/dashboard/ajustes'
      path: '/ajustes'
      fullPath: '/dashboard/ajustes'
      preLoaderRoute: typeof DashboardAjustesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/citas': {
      id: '/dashboard/citas'
      path: '/citas'
      fullPath: '/dashboard/citas'
      preLoaderRoute: typeof DashboardCitasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipo': {
      id: '/dashboard/equipo'
      path: '/equipo'
      fullPath: '/dashboard/equipo'
      preLoaderRoute: typeof DashboardEquipoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/horarios': {
      id: '/dashboard/horarios'
      path: '/horarios'
      fullPath: '/dashboard/horarios'
      preLoaderRoute: typeof DashboardHorariosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integraciones': {
      id: '/dashboard/integraciones'
      path: '/integraciones'
      fullPath: '/dashboard/integraciones'
      preLoaderRoute: typeof DashboardIntegracionesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/planes': {
      id: '/dashboard/planes'
      path: '/planes'
      fullPath: '/dashboard/planes'
      preLoaderRoute: typeof DashboardPlanesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profesionales': {
      id: '/dashboard/profesionales'
      path: '/profesionales'
      fullPath: '/dashboard/profesionales'
      preLoaderRoute: typeof DashboardProfesionalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/servicios': {
      id: '/dashboard/servicios'
      path: '/servicios'
      fullPath: '/dashboard/servicios'
      preLoaderRoute: typeof DashboardServiciosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sucursales': {
      id: '/dashboard/sucursales'
      path: '/sucursales'
      fullPath: '/dashboard/sucursales'
      preLoaderRoute: typeof DashboardSucursalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/send-reminders': {
      id: '/api/public/send-reminders'
      path: '/api/public/send-reminders'
      fullPath: '/api/public/send-reminders'
      preLoaderRoute: typeof ApiPublicSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-webhooks': {
      id: '/api/public/send-webhooks'
      path: '/api/public/send-webhooks'
      fullPath: '/api/public/send-webhooks'
      preLoaderRoute: typeof ApiPublicSendWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$token': {
      id: '/api/public/calendar/$token'
      path: '/api/public/calendar/$token'
      fullPath: '/api/public/calendar/$token'
      preLoaderRoute: typeof ApiPublicCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/appointments': {
      id: '/api/public/v1/appointments'
      path: '/api/public/v1/appointments'
      fullPath: '/api/public/v1/appointments'
      preLoaderRoute: typeof ApiPublicV1AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/clients': {
      id: '/api/public/v1/clients'
      path: '/api/public/v1/clients'
      fullPath: '/api/public/v1/clients'
      preLoaderRoute: typeof ApiPublicV1ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/services': {
      id: '/api/public/v1/services'
      path: '/api/public/v1/services'
      fullPath: '/api/public/v1/services'
      preLoaderRoute: typeof ApiPublicV1ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardAjustesRoute: typeof DashboardAjustesRoute
  DashboardCitasRoute: typeof DashboardCitasRoute
  DashboardClientesRoute: typeof DashboardClientesRoute
  DashboardEquipoRoute: typeof DashboardEquipoRoute
  DashboardHorariosRoute: typeof DashboardHorariosRoute
  DashboardIntegracionesRoute: typeof DashboardIntegracionesRoute
  DashboardPlanesRoute: typeof DashboardPlanesRoute
  DashboardProfesionalesRoute: typeof DashboardProfesionalesRoute
  DashboardServiciosRoute: typeof DashboardServiciosRoute
  DashboardSucursalesRoute: typeof DashboardSucursalesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardAjustesRoute: DashboardAjustesRoute,
  DashboardCitasRoute: DashboardCitasRoute,
  DashboardClientesRoute: DashboardClientesRoute,
  DashboardEquipoRoute: DashboardEquipoRoute,
  DashboardHorariosRoute: DashboardHorariosRoute,
  DashboardIntegracionesRoute: DashboardIntegracionesRoute,
  DashboardPlanesRoute: DashboardPlanesRoute,
  DashboardProfesionalesRoute: DashboardProfesionalesRoute,
  DashboardServiciosRoute: DashboardServiciosRoute,
  DashboardSucursalesRoute: DashboardSucursalesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrivacidadRoute: PrivacidadRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TerminosRoute: TerminosRoute,
  BSlugRoute: BSlugRoute,
  ApiPublicSendRemindersRoute: ApiPublicSendRemindersRoute,
  ApiPublicSendWebhooksRoute: ApiPublicSendWebhooksRoute,
  ApiPublicCalendarTokenRoute: ApiPublicCalendarTokenRoute,
  ApiPublicV1AppointmentsRoute: ApiPublicV1AppointmentsRoute,
  ApiPublicV1ClientsRoute: ApiPublicV1ClientsRoute,
  ApiPublicV1ServicesRoute: ApiPublicV1ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
