/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardServiciosRouteImport } from './routes/dashboard.servicios'
import { Route as DashboardHorariosRouteImport } from './routes/dashboard.horarios'
import { Route as DashboardClientesRouteImport } from './routes/dashboard.clientes'
import { Route as DashboardAjustesRouteImport } from './routes/dashboard.ajustes'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard.agenda'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServiciosRoute = DashboardServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHorariosRoute = DashboardHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesRoute = DashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAjustesRoute = DashboardAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/ajustes': typeof DashboardAjustesRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/horarios': typeof DashboardHorariosRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/ajustes': typeof DashboardAjustesRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/horarios': typeof DashboardHorariosRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/ajustes': typeof DashboardAjustesRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/horarios': typeof DashboardHorariosRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/agenda'
    | '/dashboard/ajustes'
    | '/dashboard/clientes'
    | '/dashboard/horarios'
    | '/dashboard/servicios'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/agenda'
    | '/dashboard/ajustes'
    | '/dashboard/clientes'
    | '/dashboard/horarios'
    | '/dashboard/servicios'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/agenda'
    | '/dashboard/ajustes'
    | '/dashboard/clientes'
    | '/dashboard/horarios'
    | '/dashboard/servicios'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/servicios': {
      id: '/dashboard/servicios'
      path: '/servicios'
      fullPath: '/dashboard/servicios'
      preLoaderRoute: typeof DashboardServiciosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/horarios': {
      id: '/dashboard/horarios'
      path: '/horarios'
      fullPath: '/dashboard/horarios'
      preLoaderRoute: typeof DashboardHorariosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ajustes': {
      id: '/dashboard/ajustes'
      path: '/ajustes'
      fullPath: '/dashboard/ajustes'
      preLoaderRoute: typeof DashboardAjustesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardAjustesRoute: typeof DashboardAjustesRoute
  DashboardClientesRoute: typeof DashboardClientesRoute
  DashboardHorariosRoute: typeof DashboardHorariosRoute
  DashboardServiciosRoute: typeof DashboardServiciosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardAjustesRoute: DashboardAjustesRoute,
  DashboardClientesRoute: DashboardClientesRoute,
  DashboardHorariosRoute: DashboardHorariosRoute,
  DashboardServiciosRoute: DashboardServiciosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
